### ISSUE TITLE
[PROCESO UX COMPLETO]

### ISSUE THREAD

**Issue by AliceInWonderDev** [mpabarca/SCL007-Social-Network#1]

**Comment by mpabarca** [comment]
GOOGLE FORM
https://docs.google.com/forms/d/1qUO9OMTc2tVmtb8nFsfc0qQ_oeK5glRNYtm4gfLQetw/edit?ts=5c4f5a2f

**Comment by mpabarca** [comment]
Issue resumen del google form listo #8

**Comment by mpabarca** [comment]
ISSUE definir usuario general listo #9
