### ISSUE TITLE
Criterios de Aceptación

### ISSUE THREAD

**Issue by AliceInWonderDev** [mpabarca/SCL007-Social-Network#10]
FROM ISSUE #9 
Juanita, mujer de 24 años, siempre ha tenido problemas con su cabello, ya que es muy seco y eso le provoca problemas en el cuero cabelludo, además su piel se irrita cuando utiliza cualquier tipo de shampoo y los remedios recomendados en la farmacia son muy caros . Por ello, tiene semanas de buscar en internet soluciones a su problema, pero ninguna le convence ya que Juanita necesita una aplicación confiable donde leer publicaciones de más personas con su mismo problema.

**Comment by AndreaVCC** [comment]
Historia Usuario 1
- Yo como usuario de la aplicación 
- Quiero registrarme  en la App
- Para ser parte de la red social 
Criterios de aceptación:
- [x] Quiero poder registrarme con mis redes sociales 
- [x] Quiero poder registrarme con mail y clave
- [x] Quiero poder recuperar la Constraseña

Historia Usuario 2
- Yo como usuario de la aplicación 
- Quiero ver publicaciones de los demás usuarios (públicos y de amigos)
- Para conocer sus problemas, soluciones y recomendaciones naturales.
Criterios de aceptación:
- [x] Quiero ver las publicaciones publicas
- [ ] Quiero ver las publicaciones de amigos

Historia Usuario 3
- Yo como usuario de la aplicación 
- Quiero publicar mis dudas en la red social
- Para obtener consejos de los usuarios y aclarar mis dudas
Criterios de aceptación:
- [x] Quiero poder publicar mis dudas en un post
- [ ] Quiero ver los comentarios de los demás usuarios en mi post

Historia Usuario 4
- Yo como usuario de la aplicación 
- Quiero publicar Recomendaciones naturales en la red social
- Para que los usuarios que pasen por los mismos problemas puedan usar lo que a mi me ha funcionado, o lugares donde conseguir los productos naturales.
Criterios de aceptación:
- [x] Quiero poder publicar en un post con mis recomendaciones
- [ ] Quiero ver los comentarios acerca de mis post de recomendaciones

Historia Usuario 5
- Yo como usuario de la aplicación 
- Quiero editar mis publicaciones
- Para poder editar faltas de ortografía, mala redacción, o para agregar información
Criterios de aceptación:
- [x] Quiero poder editar las publicaciones  todas las veces que lo requiera

Historia Usuario 6
- Yo como usuario de la aplicación 
- Quiero borrar mis publicaciones
- Para poder borrar post repetidos, o por si me arrepiento de hacer el post
Criterios de aceptación:
- [x] Quiero poder borrar mis publicaciones
- [ ] Quiero que exista una alerta en caso que presione borrar sin querer

Historia Usuario 7
- Yo como usuario de la aplicación 
- Quiero filtrar 
- Para 
Criterios de aceptación:
- [ ] 
- [ ]

**Comment by mpabarca** [comment]
MARTES 29/01: 
Primer criterio de aceptacion para pantalla 1 Login/Register
