### ISSUE TITLE
DEFINIR USUARIO GENERAL

### ISSUE THREAD

**Issue by AliceInWonderDev** [mpabarca/SCL007-Social-Network#9]

**Comment by AliceInWonderDev** [comment]
El usuario general tendrá las siguientes características:
a. Mujer 
b. De 21 a 25 años 
c. Busca mejorar algún aspecto en su físico (ya sea piel, cabello, uñas, etc.)
d. Busca solucionar una dolencia de salud leve

**Comment by AndreaVCC** [comment]
> El usuario general tendrá las siguientes características:
> a. Mujer
> b. De 21 a 25 años
> c. Busca mejorar algún aspecto en su físico (ya sea piel, cabello, uñas, etc.)
> d. Busca solucionar una dolencia de salud leve

**Comment by AndreaVCC** [comment]
> El usuario general tendrá las siguientes características:
> a. Mujer
> b. De 21 a 25 años
> c. Busca mejorar algún aspecto en su físico (ya sea piel, cabello, uñas, etc.)
> d. Busca solucionar una dolencia de salud leve
> e. Usando una app Movil

**Comment by AliceInWonderDev** [comment]
Juanita, mujer de 24 años, siempre ha tenido problemas con su cabello, ya que es muy seco y eso le provoca problemas en el cuero cabelludo, además su piel se irrita cuando utiliza cualquier tipo de shampoo y los remedios recomendados en la farmacia son muy caros . Por ello, tiene semanas de buscar en internet soluciones a su problema, pero ninguna le convence ya que Juanita necesita una aplicación confiable donde leer publicaciones de más personas con su mismo problema.
